package com.zh.base.model.bean;

import com.zh.core.model.IDataObject;

public class Authorities extends IDataObject{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5173155004863239807L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AUTHORITIES.ID
     *
     * @mbggenerated Thu Jul 10 13:32:27 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AUTHORITIES.NAME
     *
     * @mbggenerated Thu Jul 10 13:32:27 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AUTHORITIES.ENABLED
     *
     * @mbggenerated Thu Jul 10 13:32:27 CST 2014
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AUTHORITIES.MODULE
     *
     * @mbggenerated Thu Jul 10 13:32:27 CST 2014
     */
    private String module;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEnabled() {
		return enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getModule() {
		return module;
	}

	public void setModule(String module) {
		this.module = module;
	}

   
}