package com.zh.base.model.bean;

import java.util.List;

import com.zh.core.model.IDataObject;

public class Menu extends IDataObject {
    /**
	 * 
	 */
	private static final long serialVersionUID = -7081975911663334739L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.ID
     *
     * @mbggenerated Thu Jul 10 12:31:01 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.NAME
     *
     * @mbggenerated Thu Jul 10 12:31:01 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.ACTION
     *
     * @mbggenerated Thu Jul 10 12:31:01 CST 2014
     */
    
    private String nameSpace;
    
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.URL
     *
     * @mbggenerated Thu Jul 10 12:31:01 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.I18N_KEY
     *
     * @mbggenerated Thu Jul 10 12:31:01 CST 2014
     */
    private String i18nKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.ENABLED
     *
     * @mbggenerated Thu Jul 10 12:31:01 CST 2014
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.PARENTID
     *
     * @mbggenerated Thu Jul 10 12:31:01 CST 2014
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_MENU.REORDER
     *
     * @mbggenerated Thu Jul 10 12:31:01 CST 2014
     */
    private Integer reorder;
    
    private List<Menu> menuList;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getI18nKey() {
		return i18nKey;
	}

	public void setI18nKey(String i18nKey) {
		this.i18nKey = i18nKey;
	}

	public String getEnabled() {
		return enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public Integer getParentid() {
		return parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public Integer getReorder() {
		return reorder;
	}

	public void setReorder(Integer reorder) {
		this.reorder = reorder;
	}

	public List<Menu> getMenuList() {
		return menuList;
	}

	public void setMenuList(List<Menu> menuList) {
		this.menuList = menuList;
	}

	public String getNameSpace() {
		return nameSpace;
	}

	public void setNameSpace(String nameSpace) {
		this.nameSpace = nameSpace;
	}

}