package com.zh.base.model.bean;

import com.zh.core.model.IDataObject;

public class Param extends IDataObject {
    /**
	 * 
	 */
	private static final long serialVersionUID = -7771524214491106711L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.ID
     *
     * @mbggenerated Tue Jul 22 08:05:32 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.EMAILSERVICE
     *
     * @mbggenerated Tue Jul 22 08:05:32 CST 2014
     */
    private String emailservice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.EMAILFORM
     *
     * @mbggenerated Tue Jul 22 08:05:32 CST 2014
     */
    private String emailform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.EMAILUSERNAME
     *
     * @mbggenerated Tue Jul 22 08:05:32 CST 2014
     */
    private String emailusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.EMAILPASSWORD
     *
     * @mbggenerated Tue Jul 22 08:05:32 CST 2014
     */
    private String emailpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.EMAILISAUTH
     *
     * @mbggenerated Tue Jul 22 08:05:32 CST 2014
     */
    private String emailisauth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_PARAM.EMAILURLPASSWORD
     *
     * @mbggenerated Tue Jul 22 08:05:32 CST 2014
     */
    private String emailurlpassword;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmailservice() {
		return emailservice;
	}

	public void setEmailservice(String emailservice) {
		this.emailservice = emailservice;
	}

	public String getEmailform() {
		return emailform;
	}

	public void setEmailform(String emailform) {
		this.emailform = emailform;
	}

	public String getEmailusername() {
		return emailusername;
	}

	public void setEmailusername(String emailusername) {
		this.emailusername = emailusername;
	}

	public String getEmailpassword() {
		return emailpassword;
	}

	public void setEmailpassword(String emailpassword) {
		this.emailpassword = emailpassword;
	}

	public String getEmailisauth() {
		return emailisauth;
	}

	public void setEmailisauth(String emailisauth) {
		this.emailisauth = emailisauth;
	}

	public String getEmailurlpassword() {
		return emailurlpassword;
	}

	public void setEmailurlpassword(String emailurlpassword) {
		this.emailurlpassword = emailurlpassword;
	}

 
}