package com.zh.base.model.bean;

import java.util.Date;

import com.zh.core.model.IDataObject;

public class User extends IDataObject{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5890716186717790089L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.id
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.loginName
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.userPassword
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.name
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.ENABLED
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.userType
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.role_id
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.enterprise_id
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.email
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.age
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private Date age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.sex
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.phone
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.qq
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.mobile_number
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String mobileNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.entryTime
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private Date entryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.address
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.education_background
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private String educationBackground;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.CreateTime
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.updateTime
     *
     * @mbggenerated Wed Jul 09 16:36:05 CST 2014
     */
    private Date updateTime;
    
    
    /***
     * 重置密码时候保存的随机数
     */
    private String nonce;
    
	@Override
	public boolean equals(Object obj) {
		boolean bool = false;
		if(null != obj && obj instanceof User)
		{
			User u = (User)obj;
			if(this.id.toString().equals(u.getId()))
			{
				bool = true;
			}
		}
		return bool;
	}

	@Override
	public int hashCode() {
		int result = 2;
		String str = "User";
	       result = str.hashCode()*result;
	       if(null != id )
	       {
	    	   result = result + (int)id;
	       }else if(null != loginName)
	       {
	    	   result = result + loginName.hashCode();
	       }
		return result;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getUserPassword() {
		return userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEnabled() {
		return enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getAge() {
		return age;
	}

	public void setAge(Date age) {
		this.age = age;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public Date getEntryTime() {
		return entryTime;
	}

	public void setEntryTime(Date entryTime) {
		this.entryTime = entryTime;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEducationBackground() {
		return educationBackground;
	}

	public void setEducationBackground(String educationBackground) {
		this.educationBackground = educationBackground;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getNonce() {
		return nonce;
	}

	public void setNonce(String nonce) {
		this.nonce = nonce;
	}

}