package com.zh.web.model.bean;

import com.zh.core.model.IDataObject;


/**
 * 文件信息
 * @author taozhaoping 26078
 * @author mail taozhaoping@gmail.com
 */
public class FileInfo extends IDataObject{
    /**
	 * 
	 */
	private static final long serialVersionUID = -4083071506500899088L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEINFO.ID
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEINFO.NAME
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEINFO.NAMETYPE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    private String nametype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEINFO.TYPE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEINFO.DESCR
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEINFO.CREATEDATE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEINFO.UPDATEDATE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    private String updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEINFO.STATE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FILEINFO.TECHNOLOGICALPROCESSID
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    private Integer technologicalprocessid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEINFO.ID
     *
     * @return the value of T_FILEINFO.ID
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEINFO.ID
     *
     * @param id the value for T_FILEINFO.ID
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEINFO.NAME
     *
     * @return the value of T_FILEINFO.NAME
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEINFO.NAME
     *
     * @param name the value for T_FILEINFO.NAME
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEINFO.NAMETYPE
     *
     * @return the value of T_FILEINFO.NAMETYPE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public String getNametype() {
        return nametype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEINFO.NAMETYPE
     *
     * @param nametype the value for T_FILEINFO.NAMETYPE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public void setNametype(String nametype) {
        this.nametype = nametype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEINFO.TYPE
     *
     * @return the value of T_FILEINFO.TYPE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEINFO.TYPE
     *
     * @param type the value for T_FILEINFO.TYPE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEINFO.DESCR
     *
     * @return the value of T_FILEINFO.DESCR
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEINFO.DESCR
     *
     * @param descr the value for T_FILEINFO.DESCR
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEINFO.CREATEDATE
     *
     * @return the value of T_FILEINFO.CREATEDATE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEINFO.CREATEDATE
     *
     * @param createdate the value for T_FILEINFO.CREATEDATE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEINFO.UPDATEDATE
     *
     * @return the value of T_FILEINFO.UPDATEDATE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public String getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEINFO.UPDATEDATE
     *
     * @param updatedate the value for T_FILEINFO.UPDATEDATE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public void setUpdatedate(String updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEINFO.STATE
     *
     * @return the value of T_FILEINFO.STATE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEINFO.STATE
     *
     * @param state the value for T_FILEINFO.STATE
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FILEINFO.TECHNOLOGICALPROCESSID
     *
     * @return the value of T_FILEINFO.TECHNOLOGICALPROCESSID
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public Integer getTechnologicalprocessid() {
        return technologicalprocessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FILEINFO.TECHNOLOGICALPROCESSID
     *
     * @param technologicalprocessid the value for T_FILEINFO.TECHNOLOGICALPROCESSID
     *
     * @mbggenerated Sat Aug 16 17:00:38 CST 2014
     */
    public void setTechnologicalprocessid(Integer technologicalprocessid) {
        this.technologicalprocessid = technologicalprocessid;
    }
}